version: "3.5"

services:
    app:
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            DATABASE_URL: postgres://db_for_my_test_app_user:kNa63nTroqfwpdtwRnsdtfOLhlfZPjLM@dpg-cgg1emm4daddcg1s40t0-a.frankfurt-postgres.render.com/db_for_my_test_app
        ports:
            - "8080:5000"
